services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./api:/usr/src/app/api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      AGENT_URL: http://agent:8000
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
      - agent

  agent:
    build:
      dockerfile: Dockerfile
      context: ./agent 
    volumes:
      - ./agent:/usr/src/app/agent
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres

  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - tasks-postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  tasks-postgres: